typography_spectrum: 0.37932215547447307
color:
  brandStrength: 0.0017078767950176308
  lightness: 0.941721839208414
  saturation: 0.7777042921520032
  rhythmicContrast: 0.7363966014768264
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
github: true
layout_spectrum: 0.23508338409605078
analytics:
  facebook: '1418723908206559'
  google: UA-101719936-1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/aed2b3aa-9737-4764-8ecb-7ca7f345d314.png
name: Silev1n
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Instagram
    url: 'https://www.instagram.com/silev1n'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Silev1n'
    type: external
  - name: Google+
    url: 'https://plus.google.com/108277587797880792697'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/c/Silev1n'
    type: external
  - name: Work with me
    id: 06f45079-b43f-48ed-ba0a-4ed74f59fe00
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d91d190b-c1bc-49a8-a0f9-100135fd1868.png
title: Welcome to Silev1n
content: []
description: >-
  A travel & lifestyle blog featuring travel tips, and #iphone photography from
  around the world.
purpose:
  - type: external
    url: 'https://www.instagram.com/silev1n'
    label: FOLLOW @SILEV1N ON INSTAGRAM
  - type: contact
    url: 'mailto:silev1n@icloud.com'
    label: WORK WITH ME
